[AirQualityPage] Create page
dsila2017/EcoTracker-App pull request #2
Opened 2023-12-01 10:59 UTC by natikhiz

2023-12-01 11:27 UTC, Jamatta requested changes
- Remove comment
- Change button and ipnut style to be consistancy

button 
button.setTitle("Search", for: .normal)
        button.backgroundColor = CustomColors.primary
        button.setTitleColor(CustomColors.white, for: .normal)
        button.translatesAutoresizingMaskIntoConstraints = false
        button.layer.cornerRadius = 10
        button.clipsToBounds = true
        button.titleLabel?.font = UIFont.boldSystemFont(ofSize: 18)
        
        input
        
         textField.placeholder = "Search by address"
        textField.backgroundColor = CustomColors.darkGray
        textField.textColor = CustomColors.white
        textField.translatesAutoresizingMaskIntoConstraints = false
        textField.layer.cornerRadius = 10
        textField.clipsToBounds = true
        textField.textAlignment = .left
        textField.tintColor = CustomColors.white
        
- Make sun symbol smaller

2023-12-01 15:07 UTC, dsila2017 requested changes

2023-12-01 17:37 UTC, natikhiz commented on EcoTracker App/EcoTracker App/Scenes/AirQualityPage/View/AirQualityPageViewController.swift
> +    @objc private func fetchDataButtonTapped() {
დეკონმპოზიციისთვის მგონი აჯობებს ცალკე ფუნქციაში იყოს გატანილი, ასე ღილაკის შექმნა იბერება და არაა კარგი

2023-12-01 19:16 UTC, natikhiz commented on EcoTracker App/EcoTracker App/Scenes/AirQualityPage/View/AirQualityPageViewController.swift
> +    @objc private func fetchDataButtonTapped() {
addAction-ს ვიყენებ და objc-ს არა

2023-12-01 19:33 UTC, razmaa approved these changes

2023-12-01 19:33 UTC, dsila2017 approved these changes

2023-12-01 19:34 UTC, aberidze approved these changes
Nice job

2023-12-01 19:35 UTC, Jamatta approved these changes

2023-12-01 19:37 UTC, merged

2023-12-03 21:48 UTC, NanaJimsheleishvili commented on EcoTracker App/EcoTracker App/App/SceneDelegate.swift
> +         // Use this method to optionally configure and attach the UIWindow `window` to the provided UIWindowScene `scene`.
ერთი ზედმეტი სფეისითაა მთელი კოდი გამოსული და გასასწორებელია კოდის მთელი alignment 
კონტროლ და i ით

2023-12-03 21:48 UTC, NanaJimsheleishvili commented on EcoTracker App/EcoTracker App/Extensions/UIColor Extension.swift
> +    static let primary = CustomColors.primary
propertyეს უნდა იყოს init ის მაღლა

2023-12-03 21:48 UTC, NanaJimsheleishvili commented on EcoTracker App/EcoTracker App/Scenes/AirQualityPage/View/AirQualityPageViewController.swift
> +        DispatchQueue.global().async { [weak self] in
[weak self] არჭირდება

2023-12-03 21:48 UTC, NanaJimsheleishvili commented on EcoTracker App/EcoTracker App/Scenes/AirQualityPage/View/AirQualityPageViewController.swift
> +        DispatchQueue.main.async { [weak self] in
არც აქ

2023-12-03 21:48 UTC, NanaJimsheleishvili commented on EcoTracker App/EcoTracker App/Scenes/AirQualityPage/View/AirQualityPageViewController.swift
> +            guard let self = self else { return }
`guard let self else { return }`

2023-12-03 21:48 UTC, NanaJimsheleishvili commented on EcoTracker App/EcoTracker App/Scenes/AirQualityPage/ViewModel/AirQualityPageViewModel.swift
> +        network.request(with: url) { (result: Result<CountriesResponse, Error>) in
weak self

2023-12-03 21:48 UTC, NanaJimsheleishvili commented on EcoTracker App/EcoTracker App/Scenes/AirQualityPage/ViewModel/AirQualityPageViewModel.swift
> +        network.request(with: url) { (result: Result<StatesResponse, Error>) in
აქაც

2023-12-03 21:48 UTC, NanaJimsheleishvili commented on EcoTracker App/EcoTracker App/Scenes/AirQualityPage/ViewModel/AirQualityPageViewModel.swift
> +        network.request(with: url) { (result: Result<CitiesResponse, Error>) in
აქაც